development:
  host: localhost
  database: ta_queue_development

test:
  host: localhost
  database: ta_queue_test

# set these environment variables on your prod server
production:
  host: localhost
  database: ta_queue_production
  username: <%= ENV['MONGOID_USERNAME'] %>
  password: <%= ENV['MONGOID_PASSWORD'] %>
#  port: <%= ENV['MONGOID_PORT'] %>
#  database: <%= ENV['MONGOID_DATABASE'] %>
  # slaves:
  #   - host: slave1.local
  #     port: 27018
  #   - host: slave2.local
  #     port: 27019
